### ISSUE TITLE
App icon needs to be designed

### ISSUE THREAD

**Issue by akozlik** [cforlando/PetAdoption-iOS#23]

**Comment by Erin-Denton** [comment]
![app store copy](https://cloud.githubusercontent.com/assets/12246041/15087763/1c2df4ac-13ba-11e6-9f55-b5664accfcb0.png)
![app store copy 2x](https://cloud.githubusercontent.com/assets/12246041/15087765/1c2f49e2-13ba-11e6-9d43-77ac38e1f821.png)
![itunesartwork](https://cloud.githubusercontent.com/assets/12246041/15087766/1c310156-13ba-11e6-83a0-944bb840cc13.png)
![itunesartwork 2x](https://cloud.githubusercontent.com/assets/12246041/15087764/1c2ef0e6-13ba-11e6-88d9-be821c2f86dd.png)

**Comment by Erin-Denton** [comment]
:D ?
