### ISSUE TITLE
Implement image caching

### ISSUE THREAD

**Issue by WERUreo** [cforlando/PetAdoption-iOS#36]
I would like to be able to cache images downloaded by the API so we aren't constantly having to download images.  AlamofireImage makes this relatively painless.

**Comment by akozlik** [comment]
This issue is not ready to be worked on. It appears that the images are still being loaded from placeholders. Once images are loading from the correct sources we can come back and implement caching.

**Comment by akozlik** [comment]
I was a dumbass. Please ignore.

**Comment by akozlik** [comment]
dun
