### ISSUE TITLE
[Bug] Unable to load pet listing

### ISSUE THREAD

**Issue by LondonAtlas** [cforlando/PetAdoption-iOS#53]
The following error returns when trying to load pets from the server.

`<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /api/v2/list was not found on this server.</p>\n</body></html>\n`

**Comment by LondonAtlas** [comment]
This is the end point that is failing:` http://cfo-pet-adoption-server.eastus.cloudapp.azure.com/api/v2/list`

**Comment by khalidhoffman** [comment]
@LondonAtlas We've gone through a few domains at this point already. Sorry for the confusion. I've put up a free heroku instance at [pet-adoption-server.herokuapp.com](https://pet-adoption-server.herokuapp.com) You can find the endpoint you're looking for at: `https://pet-adoption-server.herokuapp.com/api/v2/species/all/animals/list`. [Here's a list of all the current routes](https://github.com/cforlando/PetAdoption-API#api-reference)
